### ISSUE TITLE
Feedback: Jacob Crane

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#107]
**Which page:** `w/jacob-crane.md`
**Your feedback:** 
<additional Bio:
references: Jacob cagematch profile: https://www.cagematch.net/?id=2&nr=20559
AKA: Kuba Kamiński / Adept Kuba (MZW)
Pseudonyms: "The Perfect Man" "The Top Guy Everywhere"
Trained by: Justin Joy, Joe E Legend, Shadow, Asmund

2017: PpW early days & Transition to MZW
Before his MZW debut Jacob Crane made a few apperances in PpW federation back in Warsaw, where he took part in backyard matches against Jake Young and Hades (now Olgierd).
His first stint in PpW was short-lived, as he began his pro wrestling training in MZW Academy in Głuchołazy at 2017.

2017-2021 MZW
Jacob made his in-ring debut for MZW as "Kuba Kamiński" (his real name) at MZW Freak Show at 2017-12-02 in a ten man Battle Royal. His first singles match took place during MZW Project 1: New Beggining at 2018-10-13 where he faced & lost to Rafael Kid. That marks his debut under the "Jacob Crane" ringname. 
Jacob continued his regular MZW apperances up until 2021 MZW Project Basement 3. He however made an official farawell to MZW at MZW Project 8: Golden Road Finals, where he officialy announced his departure from the company.
Jacob quickly began taking bookings abroad. He made his international debut at Next Step Wrestling show at 2018-10-27 and continued regualar apperances at Central-European independent scene ever since.

2021-2022 PTW
not much to add about this part here.

2022-2024 Return to PpW & International Career
After his dismissal from PTW Crane announced his relocation to Germany with focus on bookings in germany itself (Mostly for wXw & wXw Academy). He also made his comeback to PpW after over five years of absence, re-debuting in a match against Steve Kuningas at PpW: Brak Mi Słów at 2022-09-10. Since then he made regular apperances for PpW, as well as taking up role as head-coach in PpW Dojo, training new-generation of wrestlers such as Gustav Griffin & Goblin, as well as improving PpW Orginal wrestlers in-ring abilities.
After his 3-month stint in japaneese promotion BJW it was announced, that Jacob Crane will return at PpW: Ale Grzeje in a rematch against Gabriel Queen. Along that info it was also announced, that Jacob will run a summer wrestling course under PpW brand as head coach. 
Summer Wrestling Camp was a introduction for creation a "Ewenement Dojo" a Warsaw-based wrestling dojo, where Jacob would be one of the head coaches. (I would suggest making new article about that)

**Comment by k3rni** [comment]
Added in a08288d
