### ISSUE TITLE
New Article: Ewenement Dojo

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#108]
Ewenement Dojo - Warszawska Szkoła Wrestlingu
References: https://www.facebook.com/profile.php?id=61560762345187 - Ewenement Dojo Facebook Fanpage

Years active: July 2024-current (previously as PpW Dojo)
Location: Warsaw, Poland
Coaching Staff:
- Jacob Crane - Head Coach
- Biesiad Strong - Martial Arts Coach

Alumni:
- Gustav Gryffin (PpW Dojo) 
- Goblin (PpW Dojo)
- Mister Z (PpW Dojo)
- Biesiad Strong (PpW Dojo)
- TBD
History:

Foundation of Ewenement Dojo was announced at 2024-06-08 at PpW Ledwo Legalne IV show, later followed by creation of Facebook & Instagram profiles of the Dojo. Ewenement Dojo is an evolution of PpW Dojo, which operated previously as semi-official and partially closed for rookies. In practice it was an auxiliary dojo without a consistent schedule, where PpW talent would train under Jacob Crane & Justin Joy.
The creation of Ewenement Dojo was preceded by the Summer Wrestling Camp organised by PpW with Jacob Crane as Head Coach fresh after his return from a 3-month stint in BJW in Japan. 
For the first time in Polish Wrestling's history it was announced that the training sessions will be hosted mainly on weekly basis instead of weekend-only two day training regimes. This change was inspired by German dojos such as wXw Academy, and martial arts dojos. 

Photos:
![Ewenement Dojo Logo](https://github.com/tpwres/teczki-polskiego-wrestlingu/assets/173069994/4ca9bc55-4750-49d5-a104-5348135f2389) - Ewenement Dojo Logo
![image](https://github.com/tpwres/teczki-polskiego-wrestlingu/assets/173069994/66056789-a41a-4ea4-b59f-a68b9c95d99a) - Announcement of Ewenenement Dojo Head Coach - Jacob Crane
![image](https://github.com/tpwres/teczki-polskiego-wrestlingu/assets/173069994/a5698fd6-7613-45a8-a826-95f9f740c7f1) - Announcement of Ewenement Dojo Martial Arts Coach - Biesiad Strong

**Comment by k3rni** [comment]
Added in 108d25e
