### ISSUE TITLE
Feedback: PTW#4: The Mystery

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#111]
**Which page:** `e/ptw/2023-06-25-ptw-4-mystery.md`
**Your feedback:** 
<change "Cryptic promos from [Sinister](https://tpwres.pl/w/sinister/) aired all throughout the build-up to this show, and the show's title refers to them." to "Cryptic promos from [Sinister](https://tpwres.pl/w/sinister/) aired all throughout the build-up to this show, and the show's title **might be referring** to them."

reason for correction:
PTW always treated the themes of their shows rather loosely, with events from trailers not impacting PTW canon at all - refer post-apo Revolucja, cyberpunk club at Blackout.
Mystery's trailer featured Puncher beating down a hooded figure tied to the chair in the middle of PTW ring and PTW crew playing the roles of forensic analysts, criminals and policemen - totally non-canon.
https://www.youtube.com/watch?v=66tEGH6vkns&t=19s 
Also Mystery theme was picked up in different forms than just Sinister's reveal - there was also a kidnapping of Rzeźniczek and Paka's Mystery Machine entrance.>

**Comment by k3rni** [comment]
Updated in 4ed92a4
