### ISSUE TITLE
Feedback: PTW x RyuCon 3

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#186]
**Which page:** `e/ptw/2024-07-07-ptw-x-ryucon.md`
**Your feedback:** 
<PTW x Ryucon 3 full card & results:

1. Max Speed def. Alex Brave (FKA Srafał) - Tables Match
2. Maverick (HUN) def. Luke Bjorn (ITA), Rust (ITA) & Blaze (Balla Balazs from HUN) - Fatal 4 Way for PTW Contract
3. Puncher def. Miyagi Shida - Puncher open challenge for PTW & WWA Championship
5. Nano Lopez def. Erik Solthir
6. Vincent Caravaggio & Svedberg def. Gulyas Bros - Tag Team Match
7. Spartan def. Joseph Conners
8. Diana Strong def. Iva Kolasky
staff: 
Host, ring announcer, General Manager: Arkadiusz Pawłowski
Referee: Klaudiusz

reference: https://mywrestling.com.pl/ptw-ryucon-3-wyniki/ + Insider info to correct some stuff>

**Comment by k3rni** [comment]
Added in f5ade04
