### ISSUE TITLE
Feedback: Polska Akademia Wrestlingu

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#187]
**Which page:** `o/paw.md`
**Your feedback:** 
<Some updates in 2024 section:

Location Update (dates & dojo locations if known):
Głuchołazy (2017-2018) [GOSiR Głuchołazy]
Wrocław (2018-10.2021) [Czasoprzestrzeń, "Blaszak" Facility & Facility at Aleksandra Ostrowskiego st.]
Toruń: (10.2021-10.2022) [Liceum Ogólnokształcące nr.2]
Wrocław (10.2022-04.2024) [Czasoprzestrzeń]
Kępno (04.2024-) [Kępno Dojo or smth]

2019-2023 edit:

Since october 2022 PAW made a return to Wroclaw & Czasoprzestrzeń, where the would irregulary host training sessions, while being rarely active at their own Facebook profile. Trainees attendance back then would vary between 3-5 rookies every weekend.

2024- Moving to Kępno and revival

Since April 2024 PAW has made yet another move to Kępno - small town located approx. 1 hour drive east of Wroclaw, where they continued their trainings. At June 14th they announced their 5-day wrestling summer camp scheduled to be hosted 19-24 August at their new facility in Kępno. 
At 29th of June a photo was posted at PAW fanpage. The picture shows PAW trainees along with many ex-MZW, ex-PTW and PpW wrestlers.

New screenshot:
Potential descryption: Photo posted on PAW fanpage. Description says: "Another weekend. Another training with "new faces" on it. And one conclusion: The Ring Unites People." Besides PAW trainees there are multiple ex-PTW/MZW wrestlers visible: Samson, Marco Hammers, Disco Pablo, Dziedzic, Aron Wake, Sambor & Rafi Rarytas

![image](https://github.com/tpwres/teczki-polskiego-wrestlingu/assets/173069994/c038241b-71fa-4db5-8312-63daa362f13a)

**Comment by k3rni** [comment]
Added in a4dcebe, corrections follow in #188
