### ISSUE TITLE
Feedback: Polska Akademia Wrestlingu

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#188]
**Which page:** `o/paw.md`
**Your feedback:** 
<PAW training facilities:
"Blaszak" was a facility at Leona Popielskiego Street (trivia: this is the spot, where the parts of MZW/PAW ring was stolen in late 2019)
Later, PAW moved to other facility at Aleksandra Ostrowskiego Street, where PRoject Basement was taped

Two different locations! (You can add Popielskiego as a venue for Basements btw)

**Comment by k3rni** [comment]
Added in 6f20368, later added venues to the Basement events and a basic page for Ostrowskiego.
