### ISSUE TITLE
New Article: PTW Academy

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#189]
<
Basic Info:
Years active: 2021-current
Location: 
1. Chorzów (2021-04.2024) [PTW Performance Center]
2. Kozłów (04.2024-) [Dworek pod Platanami]

Coaching Staff:
Active:
- Arkadiusz Pawłowski - Owner, Head & Promo Coach (2021-)
- Nano Lopez - Coach (2021-)
- Renegade - Guest Coach (2022-)
- Krampus - Guest Coach (2022-)

Former:
- Taras - Coach (2022-2024)
- Disco Pablo - Assistant Coach (2022-2024)
- Justin Joy - Coach (2022-2023)
- Jacob Crane - Occasional / Part Time Coach (2021-2022)
- Axel Fox - Occasional / Part Time Coach (2021-2024)
- Gracjan Korpo - Coach (2021)
- Joe E. Legend - Guest Coach (2021-2022)
- John Klinger - Guest Coach (2022-2023)

Seminary hosts:
- Santino Marella (2021-2022)
- Chris Masters (02.2022)
- Nick Aldis (02.2022)
- Axel Tischer (02.2022)
- Tucker (2023)
- Dirty Dango (2023)
- Myla Grace (2022-2023)
- Babathunder (2024)

Notable alumni:
- Puncher
- Marcelito
- Marco Hammers
- Disco Pablo
- Taras
- Syriusz Dziedzic
- Sinister
- Samson
- Arczi Czajka
- Wiktor Longman
- Spartan
- El Ogre
- Karyna
- Axel Brave
- Max Speed
- Referee Klaudiusz
- Vincent Caravaggio
- Miyagi Shida
- Taxi Złotówa
- Remo

History:

2021-2022 Fundation and celebrity era
PTW Academy started as a wrestling dojo directly linked to Prime Time Wrestling itself. First trainings began in early-2021 and most of that year class of rookies were a mix of wrestling enthusiast - mostly from silesia region - like ex-MCW wrestlers such as Dziedzic & Sinister, as well as micro-influencers and people convinced to try wrestling by Pawłowski such as Taxi Złotówa, Wiktoria Domzalska & Sylwia Cross. Besides that, a lot of ex-MZW & KPW wrestlers had transferred to PTW to train there due to personal reasons & lack of consistency in training schedule after the pandemic.
First, the orginal plan for PTW Academy was to attract not only pro wrestling enthusiasts, but also new people unaware of wrestling culture and specifics. Pawłowski frequently tried to attract non-wrestling celebrities to attend training sessions, but after PTW 1: REVOLUCJA there was visible decline in that strategy, and PTW Academy became more focused on developing their own stars.
During that years some of the talents allied themselves in a "Orginals" Group, which was a nickname given to PTW-raised talents under the influence of Pawłowski teachings & wrestling philosophy, which led to embroilment between Orginals and groups, who came to PTW from other federations (especially "The Greens") later on.

2022-2023 Golden Era
After clarification of rookies roster PTW Academy maintained regular attendance at every training session. Due to profit of having two wrestling rings in PTW Performance Center they often divided the attendees to advanced and rookie group to provide high level of training. Along with good condition of federation itself the PTW Academy also benefited from that, allowing themselves to provide high-grade coaches (such as Justin Joy & John Klinger) and frequent seminaries hosted by some of the ex-WWE and ex-TNA talents such as Nick Aldis and Axel Tischer. The training sessions were hosted almost every weekend besides few occasions such as big show weekend.

2023-2024 Crisis and downsizing
After the departure of Justin Joy & lack of the regular experienced coach most of the trainings responsibilites were taken up by Taras, Disco Pablo & Nano Lopez with occasional apperances from Axel Fox or Renegade. Overall attendance at training weekends went slightly down due to various crisises connected directly to PTW federation itself.
PTW Academy, along with federation itself changed its location at April 2024, when they moved from PTW Performance Center at Chorzów, to Dworek pod Platanami in Kozłów.
During the huge wave of PTW Exits after PTW Total Blast from the Past huge part of coaching staff, talent and rookies left the federation.

**Comment by SewiTheRef** [comment]
btw: coach titles:
Head Coach - PTW w sumie nie licząc Pawłowskiego nigdy nie miało jakby głównego trenera, a Pawłowski prowadził "treningi aktorskie" (czyli proma etc.) i dawał feedback po walkach treningowych
Coach - normalnie trener. Po odejściu Justina to najbardziej regularnymi trenerami on week to week basis byli Nano i Taras
Ocassional / Part Time Coach - Nie zawsze byli na miejscu, ale jako że potrafią więcej niż Orginalsi to prowadzili treningi grupy zaawansowanej jak tylko się pojawiali
Guest Coach - zawodnicy z zza granicy którzy prowadzili treningi najczęściej jak mieli booking na gali (więcej niż jednorazowo)
Seminary hosts - seminaria to jedno-dwu dniowe jednorazowe wydarzenia więc wolałem to rozróżnić od guest coach

**Comment by k3rni** [comment]
Shipped in df57c67
