### ISSUE TITLE
New Article: Praga Centrum

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#198]
<
Praga Centrum is a storage facility repurposed into a event hall. The venue itself is operated by partnership between Luzztra and Smolna - one of the best known techno clubs in Warsaw, with techno & rave parties being the most common events taking place in this venue. The venue itself distinguished itself by owning a decent-sized open backyard area with a mini beach section, as well as a huge balcony inside, which allows spectators to watch performances from a higher vantage point. The venue can fit approximately 600-700 standing spectators.

Location:
Praga Centrum is located at Praga Północ district of Warsaw at Szwedzka 2/4 street. It is located next to the "Dworzec Wileński" train station, and despite its localization on the right bank of the Vistula river, the mass transit availability is fairly decent, allowing to get there from city center in less than 25 minutes.

Events:
PpW Ewenement Haze [2024-04-20]
PpW Ledwo Legalne IV [2024-06-08]

References:
https://pragacentrum.pl/pl/ - Praga Centrum official website
https://www.facebook.com/pragacentrum?locale=pl_PL - Praga Centrum Facebook profile

**Comment by M3n747** [comment]
Poprawiłem parę słówek i drobiazgów, dodałem Ewenement Haze.

**Comment by k3rni** [comment]
Added in 7a7c389 and e93466d
