### ISSUE TITLE
Feedback: PpW Ledwo Legalne IV

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#199]
**Which page:** `e/ppw/2024-06-08-ppw-ledwo-legalne-4.md`
**Your feedback: Staff & Referees** 
<Host & Ring Announcer: Michael HT
Referees: Sędzia Karol Górski, Sędzia Kornel

**Comment by k3rni** [comment]
Updated in ce160c2
