### ISSUE TITLE
Feedback: The Greens

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#200]
**Which page:** `a/the-greens.md`
**Your feedback:** 
<some edits:
Members: Referee Sewi + add PpW :) 
Influence:
""This was mainly caused by differences in their approach to quality and wrestling philosophy, such as Justin Joy's harsh training regime, putting foreign bookings and personal development over PTW, as well as critique of Pawłowski's and the Originals' approach to "Polish wrestling without boundaries" which prevented talent from competing in other Polish federations.""

""The Greens were most active and influential in PTW since 2021 until mid-2024, when all of the remaining Greens left the federation [...]""

Trivia: (dunno if its appropriate to post but whatever)
- The Greens are also known as "The Green Monkeys" (pol. Zielone Małpy), and their official mascot is an ape/orangutan often mentioned in their "shoot" promos and Instagram notes.
- The Greens introduced their own insider championship called "ZLN GNG Championship", which is shown mostly on their social media during meetings of the group. It is a modified DFW Championship with green mainplate. The sideplates are representing Dave Batista.
>

**Comment by M3n747** [comment]
Wprowadziłem parę drobnych poprawek (literówki, ortografia, taksonomia orangutana), żeby potem nie szukać w artykule.

**Comment by k3rni** [comment]
Added in aeea50b
