### ISSUE TITLE
Issue: Big Staff Update for MZW

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#206]
<Bascially wszyscy annoucerzy, hostowie i sędziowie jakich pamiętam z mzw na każdej gali, albo znalazłem ich w materiałach archiwalnych i byłem w stanie rozpoznać (trudne się wylosowało):

MZW:
* Pokaz adeptów:
Host, Ring Announcer: Filip Cieśliński 
Commentators: Tomasz Warchoł, Piotr Walkowiak
Referees: Sędzia Matt2Hot 

References:
https://www.youtube.com/watch?v=TtRHwYXVLB0
(https://www.facebook.com/photo/?fbid=443915825752649&set=ms.c.eJw9zdkNRFEIAtCOJi640H9jk~_j1fZ4gCDg1vKPCkv7DmgalBz9TOsXiGVjLuceaz6HTRz2nzn7dfQWlg337tf~%3B03LI5zjZ98A9GfSPE.bps.a.443915289086036)

* MZW in Smolec:
Host, Ring Announcer: Filip Cieśliński
Referees: 2 unknown refs 

References:
https://www.youtube.com/watch?v=govjBMLhU3E

* MZW Wakacyjny Slam:
Host, Ring Announcer: Filip Cieśliński
Referees: Sędzia Piotr (Mr. B) + 1x unko

References:
https://www.facebook.com/photo/?fbid=500636040080627&set=a.500635830080648

* MZW Fenix Boxing Night:
Referees: 1x unknown boxing referee

* MZW Wrestlefans Party:
Host, Ring Announcer: Piotr Walkowiak
Referees: Sędzia Piotr

References: 
https://www.youtube.com/watch?v=kvemG5gWOUo

* MZW Podziemny Krąg:
Host: no clue
Referee: Unknown Ref 

References: https://www.youtube.com/watch?v=KVnSKos72hs

MZW Charity Show:
Host: unknown host
Referees: Sędzia Piotr

ref: https://www.youtube.com/watch?v=2IaA9_sT6Fo

MZW Wyciskanie sztangi 2k15:
Host: Tomasz Warchoł
Referees: Unknown Ref

MZW Pre-War:
Host, Announcer Jędruś Bułecka
Referees: Jędruś Bułecka & Sędzia Piotr

MZW Champions War:
Host & Announcers: Tomasz Warchoł, Filip Cieśliński 
Referees: Sędzia Piotr + Unknown Referee

MZW Bieg Wopisty:
Host & Announcer: n/a
Referee: 1x unknown referee

MZW Champions War II:
Host & Announcers : Tomasz Warchoł & El Muchacho
Referees: 1x unknown referee
Ref: https://mywrestling.com.pl/mzw-champions-war-ii-relacja-po-gali/

MZW Wyciskanie sztangi 2016:
Host & Announcer: Tomasz Warchoł
Referees: 1x Unknown Ref

MZW Beatdown:
Host & Announcer: Tomasz Warchoł
Referees: 1x Unknown Ref

MZW Lucha Show:
Host: N/A
Referees: 1x unknown ref (Chris Hunter z DFW? https://www.youtube.com/watch?v=Wucpm6M5WEQ ) 

MZW Revolution:
Host & Announcer: Tomasz Warchoł
Commentators: Adam "Omega" Sekuła & Wojciech "Vice" Baranowski
Referees: Sędzia Kral Slova Kuba (CZE) (https://www.facebook.com/photo/?fbid=892854787525415&set=a.422497321227833)

MZW WOŚP 2017:
Host & Announcer: Tomasz Warchoł
Referees: 1x unknown referee (Sędzia BORO? https://www.youtube.com/watch?v=XDN1pj08KEo)

MZW Beatdown II:
Host & Announcer: Tomasz Warchoł
Referees: Sędzia Kral

MZW Champions War III
Host: Jędruś Bułecka
Announcer: Tomasz Warchoł
Referees: Sędzia Kral

MZW Freak Show:
Host: Jędruś Bułecka
Announcer: Tomasz Warchoł
Referees: 1x unknown referee

MZW Big Rumble:
Host & Ring Announcer: Tomasz Warchoł
Referees: też Tomasz Warchoł (XD) & Sędzia Rafael (Rafael Kid)

Project 1:
Host & annoucer: Tomasz Warchoł
Referee: Sędzia Tobias (GER)

Project 2: 
Host & annoucer: Tomasz Warchoł
Referees: Sędzia Matt2Hot, 1x unknown (HUN?) Ref, 

Project 3:
Host & annoucer: Tomasz Warchoł
Referees: Sędzia Tobias, Sędzia Matt2Hot

Project 4:
Host & annoucer: Tomasz Warchoł
Referees: Sędzia Tobias, Sędzia Matt2Hot

Project 5:
Host & annoucer: Tomasz Warchoł
Referees: Sędzia Tobias, Sędzia Matt2Hot

Project 6:
Host & Announer: Mateusz Czarnecki
Referees: Sędzia Michał, Sędzia Tobias

Project 7:
Host & Announer: Mateusz Czarnecki
Referees: Sędzia Michał, Sędzia Tobias

Project Basement 1:
Host: Konrad Von Koch
Ring Announer: Mateusz Czarnecki
Referees: Sędzia Michał, Sędzia Seweryn

Project Basement 2:
Host: Konrad Von Koch
Ring Announer: Mateusz Czarnecki
Referees: Sędzia Michał, Sędzia Seweryn
Commentary: Jędrzej Jezierski & Piotr Małecki

Project Basement 3:
Host: Konrad Von Koch
Ring Announer: Mateusz Czarnecki
Referees: Sędzia Michał, Sędzia Seweryn
Commentary: Jędrzej Jezierski & Piotr Małecki

Project Basement 4:
Host: Konrad Von Koch
Referees: Sędzia Michał, 

Project Basement 5&6 
Host: Konrad Von Koch
Ring Announer: Mateusz Czarnecki
Referees: Sędzia Seweryn

Project 8:
Ring Announcer: Matesz Czarnecki
Referees: Sędzia Michał, Sędzia Seweryn

Game ON:
Host & Announcer: ?
Referees: 1x Unknown Ref

Żadnych Granic:
Host & Anouncer: 1x Unknown Announcer
Referees: 1x Unknown Ref, Sędzia Kornel

**Comment by k3rni** [comment]
Done in #207
