### ISSUE TITLE
Staff Update for PTW

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#210]
PTW REVOLUCJA:

Host, Ring Announcer: Arkadiusz Pawłowski
Interviewer: Krzysztof Skwarczyński
Commentators: Arek Paterek, Łukasz Baliński
Referees: Sędzia Matek

UG 1:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Matek
Commentators: Arek Paterek, Łukasz Baliński

UG 2:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Matek, Sędzia Seweryn
Commentators: Arek Paterek, Łukasz Baliński

PTW BLACKOUT:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Matek, Sędzia Seweryn
Commentators: POL: Arek Paterek, Łukasz Baliński / ENG: Dave Bradshaw, Santino Marella

UG 3:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Matek, Sędzia Seweryn

UG 4: 
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Matek, Sędzia Seweryn

UG 5: 
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Matek, Sędzia Seweryn

UG 6: 
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Matek, Sędzia Seweryn

PTW x Ryucon 1:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Matek, Sędzia Seweryn

UG 7:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Rafał

UG 8:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Matek, Sędzia Rafał

UG 9:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Matek, Sędzia Rafał

PTW LEGENDS:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Matek, Sędzia Rafał
Commentary: Arek Paterek, Łukasz "Balik" Baliński, Piotr "Showoff" Małecki
Special guest commentary for the main event: Andrzej Supron, Paweł "Boryss" Borkowski
English commentary: Santino, Lewis Costello

UG 10:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Rafał

UG 11:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Rafał

UG 12:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn

UG 13:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn

UG 14:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz

UG 15:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz

PTW THE MYSTERY:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz
Commentators: Łukasz Baliński, Arek Paterek, Piotr Showoff Małecki
Special Guest Commentator: Paweł Boryss Borkowski

PTW x RyuCon 2
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz
Commentators: Łukasz Baliński, Piotr Showoff Małecki
Post-match inteview segments: Tobiasz "Skyver" Korzybski

UG 16:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz

UG 17:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz
Commentary: Piotr "Showoff" Małecki
Special guest commentary: Diana Strong

UG 18:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz

UG 19:
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz

UG 20: 
Host, Ring Announcer: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz

PTW GOLD RUSH:
Polish commentary: Arkadiusz Paterek, Piotr Małecki, Łukasz Baliński
Special guest commentators: Andrzej Supron, Paweł Borkowski
English commentary: Santino, Lewis Costello
Ring Announcer, host, General Manager: Arkadiusz Pawłowski
Referees: Sędzia Seweryn, Sędzia Klaudiusz

**Comment by k3rni** [comment]
Shipped in #213. Still left to fill are Underground shows' commentary teams.
