### ISSUE TITLE
New Article: PTW Awards

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#216]
<
Part of: Championships and accomplishments.

PTW Awards - (pol. Nagrody podsumowujące rok, loosely translated as "End of The Year Awards") are a concept used by PTW, where awards, simillar to cinematic Oscars, and WWE-established Slammy Awards, are given to professional wrestlers and other individuals within PTW, such as commentators and referees.

The awards were scheduled to be hosted at the end of every year, but so far only one edition was hosted at Dec 2022/Jan 2023 to summarize first chapter of PTW existance (REVOLUCJA and whole 2022).
Winners were nominated by fans by voting with reactions on PTW Fanpage post describing selected nomenees to every category.

Award granting ceremony was held during PTW Underground 12. Each of the winners was awarded a physical trophy made from plexi-glass and depicting an wrestler flexing his muscles incorporated into Kinguin PTW Logo with individual signature on base of each trophy.

Althrough most of the fan-voting process went interrupted the only controversy began during voting for Referee of The Year award, when Sędzia Seweryn and Sędzia Matek fought head-to-head battle with each other for the prize, Sędzia Rafał 
unexpectedly gained over 250 reactions while having around 40 votes so far comparing to over 150+ for both Seweryn and Matek. After short investigation it was clear that somebody decided to buy around 200 reactions from famous vietnameese bot farms. This escalated in so called "Afera Azjatycka" (Asian Afair) which concluded in disqualification from vote and suspension of Sędzia Rafał from his Referee duties, as well as deterioration of his reputation among PTW fans and other workers. Later, it turned out that the whole situation was caused by a prank made by Szymon "Modzel" Modzelewski - one of the polish pro wrestling fans who wanted to tease Arkadiusz Pawłowski by tempering with poll results.

Following categories were:

Wrestler of The Year (Wrestler Roku)
Hero of The Year (Bohater Roku)
Villain of The Year (Złoczyńca Roku)
Debutee of The Year (Debiutant Roku)
Speaker of The Year (Mówca Roku)
Tag Team of The Year (Tag Team Roku)
Commentator of The Year (Komentator Roku)
Female Wrestler of The Year (Wrestlerka Roku)
Match of The Year (Walka Roku)
Finisher of The Year (Finisher Roku)
Moment of The Year (Moment Roku)
Referee of The Year (Sędzia Roku)
Feud of The Year (Konflikt Roku)
Show of The Year (Gala Roku)

Results of fan-vote in every category: (Tabelkę można z tego zrobić jakąś czy coś)

Wrestler of The Year:
Puncher (WINNER) - 441 votes
Justin Joy - 365 votes
Joe Hendry - 65 votes
Matt Sydal - 54 votes
Krampus - 27 votes

Hero of The Year
Axel Fox (WINNER) - 215 votes
Samuray Del Sol - 40 votes
Taras - 39 votes
Nano Lopez - 19 votes
Pablo - 8 votes

Villain of The Year:
Sinister (WINNER) - 165 
Bad Bones - 60
Syriusz Dziedzic - 43
Puncher - 36
Gabriel Queen - 14

Debutee of The Year
Vic Golden (WINNER) - 130
Wiktor Longman - 93
Samson - 65
Spartan - 33
Aron Wake - 11

Speaker of The Year (Mówca Roku)
Puncher (WINNER) - 219
Taxi Złotówa - 83
Syriusz Dziedzic - 49
Sinister - 24
Axel Fox - 19

Tag Team of The Year
Pure Gold (Gabriel Queen & Vic Golden) (WINNERS) - 172
Paka (Disco Pablo, Taras & Boro) - 124
Bright Lights (Marcelito & Karol Iskra Górski) - 25

Commentator of The Year 
Arek Paterek (WINNER) - 171
Łukasz Baliński - 75
Piotr Małecki - 56
Santino - 35
Lewis Costello - 12

Female Wrestler of The Year
Diana Strong (WINNER) - 135
Myla Grace - 86
Xia Brookside - 11
Helena Sixt - 3
Gaya Glass - 0

Show of The Year
PTW 3 LEGENDS (WINNER) - 170
PTW 1 REVOLUCJA - 13
PTW 2 BLACKOUT - 11
PTW x RYUCON - 4
PTW Underground 8 - 2

Match of The Year
Justin Joy vs Axel Fox - Legends (WINNER) - 165
Matt Sydal vs Samuray Del Sol - Legends - 25
Disco Pablo vs Diana Strong vs Pure Gold - Ryucon - 16
Jonny Storm vs Jody Fleisch - Revolucja - 7
Axel Tischer vs Bad Bones - Blackout - 7

Finisher of The Year
Puncher - Wylew (WINNER) - 174
Robert Star - Stallion Cutter - 137
Paka - Blok 3D - 31
Spartan - Spartan Bomb - 28
Nano Lopez - Last Plane to Spain - 14

Moment of The Year
Justin Joy & Fox Reunion (WINNER) - 93
Drop of Joy on the table - 58
Krampus's chokeslamming Nano through the table - 15
Paka 6-man suplex - 9
Santino's Cobra - 9

Referee of The Year
Sędzia Seweryn (WINNER) - 174
Sędzia Matek - 149
Sędzia Rafał - 234 pre-disqualification (36 excluding the vietnameese bots)

Feud of The Year 
Axel Fox vs Justin Joy (WINNER) - 88
Nano Lopez vs Sinister - 60
Taxi Złotówa vs Employers - 24
Puncher vs Influencers - 12
Bad Bones vs PTW - 9

Some screens:
PTW's FB Fanpage post with poll results:
![image](https://github.com/user-attachments/assets/deb80b2f-de53-4234-9a7a-0e3fb715f9b2)
Photos of physical awards themselves:
![image](https://github.com/user-attachments/assets/3c7f6e30-3512-4b5f-8b0c-8cd4a6fbc3e4)
Example of voting graphic describing which Facebook post reaction will be for which wrestler:
![image](https://github.com/user-attachments/assets/9ad17a12-0aa6-4bf4-947f-4814bc382138)

**Comment by k3rni** [comment]
Added in e5bc4e44aefd9df2cbcb8def6c35f4cec9f0a08b and touched up in #218
