### ISSUE TITLE
Feedback: Contributing

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#225]
**Which page:** `a/contributing.md`
**Your feedback:** 
<Create event page:
PPW Hardcore friday, 20 September, 2 koła
In the closing sequence of Ale Grzeje, Michael HT announced the next show - return of classic Hardcore Friday series, set in original PPW venue, motorcycle pub 2 Koła.
Reference:
https://www.youtube.com/watch?v=UEQkSKMekCs&t=14480s&ab_channel=PpWEwenementWrestling - Ale Grzeje livestream, timestamp: 4:01:18>

**Comment by k3rni** [comment]
Added in fd528c9
