### ISSUE TITLE
New article: PTW crisis

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#232]
**Which page:** `a/contributing.md`
**Your feedback:** 
<new article: 
2024 PTW Crisis - Total Blast from The Past aftermath:
move away the sections from main PTW article, to be reworked in more coherent way later

The Stonoga controversy
On May 8th, in a move mocked by fans and PTW wrestlers alike, notorious Polish businessman and whistleblower Zbigniew Stonoga announced that he bought 1500 tickets for [PTW#6](https://tpwres.pl/e/ptw/2024-05-11-ptw-6/) and wants to distribute them for free to his supporters (who sent him money and received a numbered membership card). The next day, Stonoga posted photos of himself and the car, as well as short clips of himself in the passenger seat. Ludwiczek also posted a photo of himself and the controversial Stonoga in front of the car. Later, Stonoga announced we would hand out 50 free tickets to anyone who approached him in person at a McDonald's in Legionowo. This move prompted PTW wrestler [Taras](https://tpwres.pl/w/taras/) to seemingly cut his ties with the organization, declaring he's finally "quitting this circus".

Backlash
Other PTW personalities, such as [Disco Pablo](https://tpwres.pl/w/disco-pablo/), the aforementioned ex-commentator Piotr Małecki, and current commentator Arek Paterek, also addressed the situation. Their posts ranged from vague references to open critique. After Pablo and Taras made their comments, fans speculated about Pablo leaving PTW as well, which Pablo strongly denied. Some fans also alleged that Taras's current frustration was a result of losing the PTW Tag Team Championship, which he also denied.

The two wrestlers' criticism of PTW was also met with backlash. On PTW's public Facebook group, an account named Jakub Tyczyński (presumably a PTW personality, current or former) accused them of using their good relations with Pawłowski against other wrestlers in the past, and trying to play martyrs now.

This string of PR flops, and the apparent lack of interest from PTW, prompted WrestleFans to pull out of promoting them with immediate effect, only 3 days before the show. And in another unexpected turn of events, some of the fans who received tickets from Stonoga turned out to be [PpW](https://tpwres.pl/o/ppw/) wrestlers and personnel. This got them both free tickets for the show and some social media exposure, through photos and live video which Stonoga, unfamiliar with the wrestling scene, shared.

During this time PTW remained silent, attempted to control the situation by deleting comments pertaining to the Stonoga situation from the fan group, and continued to promote the lottery.

Silence and confusion
As this post-Gold Rush crisis was developing, PTW's social media channels remained silent.

PTW Champion [Puncher](https://tpwres.pl/w/puncher/)'s Instagram account posted a cryptic message stating "Chapter closed". This led to fans speculating that he may be the next one to leave PTW, but this turned out not to be the case. On May 17th 2024, he tweeted a [long statement](https://x.com/PuncherShow/status/1791560657453678715) comprising three screenshots where he described his road to championship, all the sacrifices he made, and accepted the blame for the PTW#6 and lottery flops. However, he also included passive-aggressive remarks about "disloyal" members of the locker room, and excessive fan criticism halting the growth of wrestling in Poland. Reactions to that statement were mixed, ranging from praise to mockery. This launched a wave of similar, shorter statements from other roster members, claiming they're going to stay with PTW through thick and thin, and would rather go down together with the organization rather than leave it because of its problems.

PTW's fate was uncertain at that point, with multiple exits and nothing in the way of official announcements. With one exception: a tribute post commemorating [John "Bad Bones" Klinger](https://tpwres.pl/w/bad-bones/), who died of a heart attack on May 20th.

On May 29th, Ryucon, a manga-themed fan convention (which previously hosted PTW events in [2022](https://tpwres.pl/e/ptw/2022-07-31-ptw-x-ryucon/) and [2023](https://tpwres.pl/e/ptw/2023-07-16-ptw-x-ryucon/)), [announced](https://www.instagram.com/p/C7ju1yYI5UF/) that they're hosting a third PTW event. However, as of June 5th, not a single mention on the show was made on PTW's official social media channels. The only activity were wrestlers [Marco Hammers](https://tpwres.pl/w/marco-hammers/) and Vincent Caravaggio feuding online, building a potential match for that show.

Ludwiczek confronts PTW
On May 23, Ludwiczek (co-host of [Gruby Temat](https://tpwres.pl/o/ptw/#new-youtube-show-gruby-temat)) took direct shots at PTW in an [Instagram post](https://www.instagram.com/p/C7RgkT-oSOb) promoting his upcoming match in Polish freak-fight organization Clout MMA (which Pawłowski was also affiliated with, and appeared as host on their shows). He claimed to "be ready for everything", and that "working with PTW and Arek [Pawłowski]" made him indestructible. In further comments he bashed PTW, Pawłowski, their ring ("mouldy mat, far from white") and the locker room. In response to that, PTW personalities such as [Taras](https://tpwres.pl/w/taras/), [Olgierd](https://tpwres.pl/w/olgierd/) and [Marco Hammers](https://tpwres.pl/w/marco-hammers/) called out the hypocrisy in his words. According to them, Ludwiczek received a hefty paycheck, free rides in luxury cars and enjoyed time with celebrities. Therefore, he had no right to bash the promotion that only benefitted him, whatever internal problems they may have. Ludwiczek explained that he was never actually employed by PTW, but rather by an outside investor, and that the lottery was his main focus. According to him, "protecting the lottery" was the reason for not confronting Pawłowski and PTW earlier. Later, several ex-PTW personalities such as [Samson](https://tpwres.pl/w/samson/), [Justin Joy](https://tpwres.pl/w/justin-joy/) and [Gabriel Queen](https://tpwres.pl/w/gabriel-queen/) joined the thread to express their disdain of Pawłowski.

Eventually both sides addressed the issue. Pawłowski, in an [interview](https://www.youtube.com/watch?v=l46enZVs2f0) for the TVreklama YouTube channel, expressed his disappointment in Ludwiczek, and called out his laziness and hypocrisy. Ludwiczek, in a [video of his own](https://www.youtube.com/watch?v=V39f6SNRUJ8&t=444s), retorted by also calling Pawłowski a lazy hypocrite.

On Monday, June 3rd, Pawłowski was the host of Clout MMA's conference promoting an upcoming show, with competitors confronting each other before the event on Saturday. In a segment promoting a handicap match between Ludwiczek & Super Mario (Mariusz Sobczak) vs Albert Sosnowski, Ludwiczek cut a promo where he was holding a PTW T-shirt in his hand. He declared that he "had worn this gift with pride, until he realized that the person who gave it to him [Pawłowski] was just a fake bitch", spat on the T-shirt and threw it away, then plugged his callout video. Pawłowski retorted with "then why the fuck are you even speaking". The two continued to trash-talk each other, blaming one another and Pawłowski raising his voice to the point of yelling. Eventually Pawłowski made his leave, while Ludwiczek remained in the panel he was invited to.

In a [follow-up interview with Puncher](https://www.youtube.com/watch?v=m2kZZBAqmuo), he called Ludwiczek a liar and asked about a potential fight between them. Puncher said that while some people find wrestling to be cringey, he actually finds freak fights cringey, adding "but who wouldn't like to punch Ludwiczek?".

Another [follow-up interview with Pawłowski](https://www.youtube.com/watch?v=F4PknaxqojM&t=73s) had Arkadiusz speaking in a trembling voice about a series of recent disasters in his life - health issues, his father's terminal illness, PTW business dwindling. He declared that he's not going to stay down on his knees, but instead rebuild his life and PTW, because it's in his nature. When discussing the events of the panel, Pawłowski dismissed Ludwiczek's challenge to fight him (presumably in Clout MMA's octagon). When asked whether he thought it was legitimate, he replied that it's probably legitimate in Ludwiczek's mind, but that he wants nothing more to do with him, and wants Ludwiczek out of his life forever. Answering a question on his future plans, he plugged the upcoming PTW x Ryucon show on July 7th 2024. This is the closest thing to an official announcement for this show that fans got so far. PTW's social media accounts were still silent.

Kanał Zero
On Thursday, June 13th, Pawłowski and [Diana Strong](https://tpwres.pl/w/diana-strong/) appeared on Kanał Zero's morning show Pobudka ("Wake-up Call"). The show was hosted by Marcin "WuWunio" Sprusiński and Izabella Krzan. One of the show's segments was a wrestling-focused interview with the guests. Unexpectedly, the hosts were very well briefed about the Polish scene and PTW's recent problems. The first questions were for Diana, regarding her sports background and the way to pro wrestling, and later the focus moved to Pawłowski. WuWunio started inquiring about PTW's state, presenting a list of wrestlers who recently left and mentioned that some of them now wrestle for [the competition](https://tpwres.pl/o/ppw/). Pawłowski, his hand forced, acknowledged the crisis, and confirmed that the lottery and [Total Blast From The Past](https://tpwres.pl/e/ptw/2024-05-11-ptw-6/) were flops. He spoke about how reading fans' criticism was very painful, because he felt exactly the same. He acknowledged that the wrestlers leaving his organization were great performers and (mostly) very good people. He then declared that the organization plans to recover from the crisis starting with the next show, [PTW x Ryucon 3](https://tpwres.pl/e/ptw/2024-07-07-ptw-x-ryucon/). Pawłowski confirmed that the reason for people leaving were disagreements about finances, booking and exclusivity. All the while, his words were countered by [Puncher](https://tpwres.pl/w/puncher/) aggressively trolling the chat, even insulting the same ex-wrestlers Pawłowski was complimenting on-screen.

When Pawłowski agreed that he was the main culprit of the downfall, Krzan pried harder, asking him about the organization's near bankrupcy. A visibly upset Pawłowski declared he will make amends, but needs some time. The hosts cut him off with a joke, that the show's previous guest (a Mr Małecki, public officer in charge of bankrupcy and property claims) may be able to help. Pawłowski joins in on the joke, but is still visibly shaken. WuWunio inquires about Rzeźniczek's (PTW's cofounder) departure, which Pawłowski confirms but declines to reveal the reasons in his absence. In the wrap-up, Diana was asked why she stayed after so many others left. She answered that she had always believed in the project, still does and has no problems working with Arek, therefore she chooses to stay. More questions about wrestling's technicalities followed, but the live chat was pressing questions about the lottery and the subject was brought up again. Once again, Pawłowski confirmed it was a spectacular fiasco, with the ticket money not even close to covering the prizes. He called it a crucial error that started a domino effect for PTW and confirmed that no lottery will be held ever again.

To wrap up the show, Pawłowski was asked what is the essence of wrestling (phrased as "istota wrestlingu" - possibly a namedrop for a [YouTube channel of the same name](https://www.youtube.com/@IstotaWrestlingu/)). He answered that connecting people, escapism, and emotional involvement are the key components of pro wrestling's appeal.>

**Comment by k3rni** [comment]
Shipped in #234
