### ISSUE TITLE
New Article: PTW Championship

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#236]
<New article:

PTW Championship

PTW Championship is a professional wrestling championship that was created and promoted by Prime Time Wrestling as their top championship. 

Statistics: (Wikipedia style ofc, kinda bland with only 1 champ but well)
First Champion: Puncher
Most Reigns: Puncher (1)
Longest Reign: Puncher (170+ days)
Oldest Champion: Puncher (27 years, 298 days)
Heaviest Champion: Puncher (102kg)

History:
Title creation was established at PTW 3: Legends show in November 2022 by Arkadiusz Pawłowski - PTW's promoter and host. Along with the title Pawłowski announced 20-person Gold Rush Rumble match (a variation of Battle Royal Match), which made place at February 2024 during PTW 5: Gold Rush. The match was won by David "Puncher" Seńko, then he became inaugural PTW Champion.

Belt Disign:
The PTW Championship has a design inspired by WWE's World Heavyweight Championship - both modern variation and classic "big gold belt" which was used in WWE and WCW. Like histroic Big Gold Belt the title has three large black and gold plates on a black leather strap. All three plates includes gold filigree with each plate outlined with rope trim to represent the three ropes of a wrestling ring. At the center of central plate, there is a big globe with black rim on which there is a "Prime Time Wrestling" and "Champion" engravings. Both on left and right side from centre of main plate there are two wrestling ring engravings.

Championship defences:
1. Puncher (c) vs. Marius Al-Alani - Underground 21 - Champion vs Champion Match
2. Puncher (c) vs Miyagi Shida - PTW x RyuCon III - Open Challenge

**Comment by k3rni** [comment]
Adding this. However, I may replace the statistics part in the future with something calculated automatically from match cards, requiring no edits to update, other than adding matches.

**Comment by k3rni** [comment]
Shipped in #238
