### ISSUE TITLE
New Article: PTW Tag Team Championship

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#245]
< 
PTW Tag Team Championship is a professional wrestling championship created and promoted by Prime Time Wrestling as their tag team division championship.

Statistics:
First Champions: PAKA (Taras, Disco Pablo & Boro)
Current Champions: Budapest Bastards (Renegade & Nitro)
Longest Reigns: PAKA (223 days)
Oldest Champion: Renegade (39 years, 99 days)
Youngest Champion: Disco Pablo (25 years, 91 days)
Heaviest Champions: PAKA - Disco Pablo & Taras (213kg)
Lightest Champions: Budapest Bastards (194kg)

History: 
The title was announced at PTW 3: Legends in November 2022 by Arkadiusz Pawłowski - PTW's owner and General Manager. The title was announced after a controversial win of Pure Gold (Gabriel Queen & Vic Golden) against PAKA (Disco Pablo & Taras). Along with creation of title Pawłowski announced tag team tournament to crown inagural champions. The finale of PTW Tag Team Championship Tournament was hosted during PTW 4: The Mystery, where PAKA defeated Pure Gold in a tables match. Due to freebird rule, Boro is also recognized as PTW Tag Team Champion.
The current champions are Budapest Bastards, who won titles during PTW 5: Gold Rush, in a Fatal 4-Way Tag Team Match agains PAKA, Sinister Kingdom, and MxM Collection.

Belt designs:
First variation of championships belts rather bulky in size with big golden octagonal rectangle as a centre plate and two smaller square-sized sideplates on a black belt . In a centre of main plate there was big and simple black letters "PTW" with "Prime Time Wrestling" under it. Bottom of the main plate also had "Tag Team Champions" label. Main plate was decorated with simple engravings  and few white crystals over and under the writings. Sideplates were rather simple, with "PTW" logo and few crystals.
First of design was rated rather poorly by audience, looking "cheap" and "bulky", so during PTW 5: Gold Rush championship belts were redesigned without any announcement.
New version of championship belts appears much slimer and smaller than the first version. Main plate is smaller with much more details, engravings and black filling instead of solid-gold plate. Central part of main plate is still taken by "PTW - Prime Time Wrestling" Logo. Sideplates are bigger than in first version, with a representation of two shaking hands - representation of tag team spirit.

Championship defences:
Champions 1: PAKA (Disco Pablo, Taras & Boro)
- PAKA (Disco Pablo & Taras) (c) **d.** Budapest Bastards - PTW x RyuCon 2 - No Contest
- Budapest Bastards **d.** PAKA (Taras & Disco Pablo), Sinister Kingdom (Syriusz Dziedzic & Sinister) & MxM Collection (Mansoor & Mason Madden) - PTW 5: Gold Rush

Champions 2: Budapest Bastards
- Budapest Bastards **d.** Axel Fox & Marcelito - PTW UG 21

Photos:
PAKA holding first variation of PTW Tag Team Championship belts:
https://scontent-waw2-2.xx.fbcdn.net/v/t39.30808-6/357107388_312637364422246_2393193064000058294_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=127cfc&_nc_ohc=dWr2mGXi6k8Q7kNvgF0lgOv&_nc_ht=scontent-waw2-2.xx&oh=00_AYCKvVmTC7jeqWQE7_QIr86pNWZwr7qeysKTSmTucFcQ-g&oe=66A79ABC

Budapest Bastards with new variation of Championship belts:
https://scontent-waw2-2.xx.fbcdn.net/v/t39.30808-6/438789497_18397493341074677_7516274195534921820_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=127cfc&_nc_ohc=hyLa1B9nMbQQ7kNvgEXJFWd&_nc_ht=scontent-waw2-2.xx&oh=00_AYDNbXw7wDh19QB6CWSuAdc_tXcKBSlMXcUx-PnvUZ4YOw&oe=66A7BAE0

**Comment by k3rni** [comment]
Shipped in #248
