### ISSUE TITLE
New Article: MZW Championship

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#247]
The MZW Championship is a professional wrestling championship created and promoted by Maniac Zone Wrestling as their top championship.

Statistics:
First Champion: Justin Joy
Most Reigns: Asmund & Shadow (2)
Longest Reign: Rafael Kid (574 days)
Shortest Reign: Asmund (2) (<1 day)
Heaviest Champion: Asmund (100kg)
Lightest Champion: Shadow (75kg)

History:
The title was introduced at MZW Champions War II, where the match for inagural champion was held between Justin Joy and Shadow, with Justin emerging as first champion. 
So far, the title was vacated twice in its history. First time Asmund vacated it immedately after winning it for second time, when he announced his retirement from in-ring competition. At MZW Project 7 the special tournament was held to establish contenders for the title. Due to pandemic the vacancy of title was prolonged until MZW Project 8: Golden Road Finals, where Rafael Kid emerged victorious from his match against MZW Project Basement winner - Aron Wake. Rafael not long after that has leaved the federation de facto vacating title the second time in history, what was announced during MZW GAME ON. 

Belt design:
MZW championship belt is rather bulky in size compared to other championships in wrestling. Championship big main plate in the middle and two smaller sideplates od sides, all of that is based on neon-green slick belt - resembling a main colour of federation. Main plate contains a big "MZW" and "Champion" signs on a steel-coloured metal plate with darker gradient in a middle, with decoration resembling a cracks or explosion. Side plates are kept in the same colour scheme, with left plate presenting the map of Poland, and right presenting white eagle - polish coat of arms.

Title History:
Champion 1: Justin Joy - 125 days
1. Justin Joy **d.** Shadow - Champions War II - Singles Match
2. Justin Joy **d.** Red Thunder - Wyciskanie Sztangi 2016 - Lumberjack Match
3. Shadow **d.** Justin Joy - MZW Beatdown - Loser Leaves MZW Match

Champion 2: Shadow - 385 days
1. Shadow **d.** Justin Joy - MZW Beatdown - Loser Leaves MZW Match
2. Shadow **d.** Prince Victor - MZW Lucha Show - Singles Match
3. Shadow **d** Asmund - MZW Revolution - Two Out of Three Falls Match
4. Shadow **d.** Franz Engel - MZW Beatdown II - Singles Match
5. Asmund **d.** Shadow - MZW Champions War III - Hardcore Match

Champion 3: Asmund - 225 days
1. Asmund **d.** Shadow - MZW Champions War III - Hardcore Match
2. Asmund **d.** Justin Joy & Franz Engel - MZW Freak Show - Triple Threat Match
3. Shadow **d.** Asmund & Stanisław Van Dobroniak - MZW Big Rumble - Triple Threat Match

Champion 4: Shadow (2) - 390 days
1. Shadow **d.** Asmund & Stanisław Van Dobroniak - MZW Big Rumble - Triple Threat Match
2. Shadow **d.** Damien Rotschild, Rafael Kid & Madman Charlie - MZW Project 2: Four - Fatal Four Way Match
3. Damien Rotschild **d.** Shadow - MZW Project 3: Black & White - Singles Match

Champion 5: Damien Rotschild - 195 days
1. Damien Rotschild **d.** Shadow - MZW Project 3: Black & White - Singles Match
2. Damien Rotschild **d.** Shadow - MZW Project 4: Open Your Match - No DQ Match
3. Damien Rotschild **d.** Justin Joy - MZW Project 5: Hero - Singles Match
4. Asmund **d.** Damien Rotschild - MZW Project 6: Death & Glory - Singles Match
Title was vacated by Asmund immedetly after wining it, due to his retirement. This resuled in title being vacated for 721 days.

Champion 6: Rafael Kid - 574 days
1. Rafael Kid **d.** Aron Wake - MZW Project 8: Golden Road FINALS - Singles Match
Title was vacated due to fact that Rafael Kid has left the federation. This was announced at MZW GAME ON and resulted in title being vacated for over 502 days. Rafael Kid reign is recognized as lasting 574 days.

Photos:
Rafael Kid with MZW Championship on his shoulder:
https://scontent-waw2-2.xx.fbcdn.net/v/t39.30808-6/242187363_2426336724177206_6064620528100943115_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=127cfc&_nc_ohc=0W00gh0Uv2QQ7kNvgEGULyL&_nc_ht=scontent-waw2-2.xx&oh=00_AYDvDW_XST5z4J-SFschg0aoCXrCE5vjEgT7dBhAhogfIg&oe=66A7DAF7

**Comment by k3rni** [comment]
Added in 7268dbe
