### ISSUE TITLE
New Article: MZW Tag Team Championship

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#251]
The MZW Tag Team Championship is a defunct professional wrestling championship which was  created and promoted by Maniac Zone Wrestling as their tag team division championship.

Statistics:
First champions: Zbójnicy (Jędruś Bułecka & Stanisław Van Dobroniak)
Last Champions: Wataha (Justin Joy & Apollo Anderson)
Longest reign: Catch Connection (Alexander Reich & Ronny Kessler) (497 days)
Oldest Champion: Jędruś Bułecka (31 years)
Youngest Champion: Apollo Anderson (18 years)
Lightest Champions: Red Thunder (77kg)

History:
The title was introduced at MZW Beatdown 2016, where the match for inagural champions was held between Zbójnicy (Jędruś Bułecka & Stanisław Van Dobroniak) and Red Thunder & Kripto with the Zbójnicy emerging victorious.
The last champions were WATAHA (Justin Joy & Apollo Anderson), however at MZW Project 3: Black & White members of WATAHA turned on each other with Apollo beating up Justin and taking both of the championship belts with him. The championship was subsequently vacated by Jędruś Bułecka at MZW Project 4: Open Your Eyes.

Belt Design:
The belt design was rather simple and modest. The main plate was elliptical  and grey-coloured with simple "MZW" logo, "Tag Team" and "Championship" texts over and under logo respectavly. Side plates were small traingle-shaped polish flags with polish coat of arms on it. All of the plates were based on simple black belt. Championships lacked any engravings or detailed design, as all of the texts, logos and decorations were simply glued on plates.

Title history:
Champions 1: Zbójnicy (Jędruś Bułecka & Stanisław Van Dobroniak) -245 days
1. Zbójnicy **d.** Kripto & Red Thunder - Tag Team Match - MZW Beatdown 2016
2. Zbójnicy **d.** Catch Connection (Alexander Reich & Ronny Kessler) - by DQ - Tag Team Match - MZW Revolution 2016
3. Storm Riders (Red Thunder & Blue Thunder) **d.** Zbójnicy - Tag Team Match - MZW Charity Show 2017

Champions 2: Storm Riders (Red Thunder & Blue Thunder) - 140 days
1. Storm Riders (Red Thunder & Blue Thunder) **d.** Zbójnicy - Tag Team Match - MZW Charity Show 2017
2. Catch Connection (Alexander Reich & Ronny Kessler) **d.** Storm Riders - Tag Team Match - MZW Champions War III

Champions 3: Catch Connection (Alexander Reich & Ronny Kessler) - 497 days
1. Catch Connection (Alexander Reich & Ronny Kessler) **d.** Storm Riders - Tag Team Match - MZW Champions War III
2. Wataha (Apollo Anderson & Justin Joy) **d.** Catch Connection (Alexander Reich & Ronny Kessler) - Tag Team Match -MZW Project 1: New Beggining

Champions 4: Wataha (Apollo Anderson & Justin Joy) - 140 days
1. Wataha (Apollo Anderson & Justin Joy) **d.** Catch Connection (Alexander Reich & Ronny Kessler) - Tag Team Match -MZW Project 1: New Beggining
After the Wataha breakup at MZW Project 4: Open Your Eyes the MZW Tag Team Championship were vacated, and subsequently deactivated by Jędruś Bułecka - MZW Owner.

Photos;
Members of Wataha (Justin Joy & Apollo Anderson) holding their championship belts:
https://scontent-waw2-2.xx.fbcdn.net/v/t1.6435-9/53110684_1539640126180208_5313596018053349376_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=13d280&_nc_ohc=0Up-IA5ZZPwQ7kNvgHRU-w7&_nc_ht=scontent-waw2-2.xx&oh=00_AYBCJFWQalyPgRcd9s6mWNZFCOSTgEV_kREM4Ynwhogt-g&oe=66CAAE90

**Comment by k3rni** [comment]
Added in 1899f79
