### ISSUE TITLE
Feedback: PpW European Ultraviolent Championship

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#259]
**Which page:** `c/ppw-european-ultraviolent-championship.md`
**Your feedback:** 
<Belt design:
The championship belt is rather bulky and sturdy-looking one. Main plate is big and circular, with big "PpW" logo in the middle, coloured in red and blue to resemble old PpW logo. Underneath there is "European Ultraviolent Championship" engraved with simple font. Centre plate is based on brown leather strap, while the rest of the belt itself is black-coloured. Sideplates are simply two small sawblades attached to the belt, and instead of classic pins the belt can be strapped together by bolts and screws, to strengthen the ultraviolent character of championship.
>

**Comment by k3rni** [comment]
Added in 79eb1aa
