### ISSUE TITLE
Feedback: Contributing

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#266]
**Which page:** `a/contributing.md`
**Your feedback:** 
<create a new page in Events:
PTW Underground 22

During a non-televised [PTW x Ryucon 3](https://tpwres.pl/e/ptw/2024-07-07-ptw-x-ryucon) PTW's owner Pan Pawłowski announced a summer camp to be held in August and finished with another PTW Underground show. Both are to be held at Kozłów, Dworek Pod Platanami - a complex containing guest rooms, sport facilities and a hall where wrestling shows can be held.

Summer camp: 19-25 August
Underground 22 - 25 August

Reference: [PTW facebook post](https://www.facebook.com/PrimeTimeWrestlingPL/posts/1228481071480296:1228481071480296?__cft__[0]=AZUtss3hBu8zOjilcWHwbsbQCyQf3K6q3NTpjhsXwiA36m61MgxLAleaW2gaEa2nKx3sM9paS4brI7hB13xRaJ4J870esYWFlmL33tovbkuJgZNb06iQ09GDJap7WBFhSszyjXCpI91kHqmw7GaFK7mX-dfUEhX1OZrp6XJrGEMmXl3uKBXtNpZkZjcVdqZdd_Km1zWdLIiFl_GNJwWz4lHN&__tn__=%2CO%2CP-R)

**Comment by iwulOG** [comment]
PTW's cover photo confirming both dates
![image](https://github.com/user-attachments/assets/6b45521f-d224-4515-a92c-f74f92d0b62a)

**Comment by k3rni** [comment]
Added in a410053,  but without the cover photo - nothing special there.
