### ISSUE TITLE
Feedback: Sędzia Kornel

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#292]
**Which page:** `w/sedzia-kornel.md`
**Your feedback:** 
<add bio

Kornel

Made his official PpW debut at PpW Najlepsza Gala w Mieście. After second match of the evening, he got into a scuffle with debuting Kapitan Bazooka, who laid out Kornel with Attitude Adjustment, writing him off for the rest of the show. Kornel addressed the attack in an interview segment, where he deemed Bazooka unproffessional https://www.youtube.com/watch?v=jPEISp3JvoU
This set up a conflict between the two that continued, mostly on social media throughout 2023. It culminated at PpW Piwo Przyjacielem Wrestlingu, where Kornel's American cousin, Kapral Kornel, defeated Kapitan Bazooka in a match.

Kornel also entered in a lengthy feud with Gustav Gryffin. Unhappy with Kornel's officiating, Gustav dubbed him a "thin dog" in a promo at Ledwo Legalne 3 [citation needed, no records of the show available], refusing to have his matches officiated by Kornel.
This resulted in Gryffin's request to have his match against Ricardo Diesel at PpW: "Czyste Intencje" officiated by Osamu and continued into Gryffin's career with his matches being officiated by other referees.

Hardcore referee
At MZW x PPW Żadnych Granic, Kornel was presented as a "referee well-versed in hardcore" and officiated a hardcore match between Biesiad and Chris X. His officiating of multiple hardcore and deathmatches, as well as taking referee bumps, sometimes resulting in bleeding (Feager v Mister Z at Ewenement Haze) earned him a nickname of "Hardcore referee">

**Comment by k3rni** [comment]
Added in 942f4d4
