### ISSUE TITLE
Feedback: PpW Piwo Przyjacielem Wrestlingu

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#311]
**Which page:** `e/ppw/2023-11-24-ppw-piwo-przyjacielem-wrestlingu.md`
**Your feedback:** 
<Bracia Pierdolec are:
Czesław Pierdolec, Gustav Gryffin billed under his canon ringname - both clad in Gryffin's singlets.

source: asking Mr Pierdolec
![image](https://github.com/user-attachments/assets/908620d3-8959-42f0-8103-7c22c172b8ed)
>

**Comment by k3rni** [comment]
Added in 21cbee9
