### ISSUE TITLE
Feedback: Legacy of Wrestling

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#320]
**Which page:** `o/low.md`
**Your feedback:** 
<trailer:
add mentions of:
PTW Intergender Championship - currently held by Hammers, with vague recognition status in PTW
mention other wrestlers present:
Jakub Linde (aka Jakob Sigmarsson, seems to have quietly dropped the name) - currently in PpW roster
Marcelito - currently a free agent >

**Comment by M3n747** [comment]
PR #322

**Comment by k3rni** [comment]
Shipped in #322
