### ISSUE TITLE
Brak ikon federacji przy Baliku i ShowOffie na liście osób

### ISSUE THREAD

**Issue by M3n747** [tpwres/teczki-polskiego-wrestlingu#392]
Na liście osób (zarówno alfabetycznej, jak i według państw), Balik i ShowOff nie mają znaczka federacji:
![image](https://github.com/user-attachments/assets/b00e25f3-5adc-4eea-b6b3-064c18148618)
![image](https://github.com/user-attachments/assets/e2079caf-4a21-4fac-9631-2e72558e7900)
![image](https://github.com/user-attachments/assets/30f03720-7c23-411c-9a16-d7cdf84e4884)

**Comment by M3n747** [comment]
Dotyczy jedynie aliasów, nie nazw głównych.

**Comment by k3rni** [comment]
Ponieważ nie są używane nigdzie - więc do aliasu nie idzie przypisać eventów. W sumie tak ma być.
