### ISSUE TITLE
Karolina na liście osób, mimo znacznika 'x:' w Gold Rushu

### ISSUE THREAD

**Issue by M3n747** [tpwres/teczki-polskiego-wrestlingu#393]
- - '[Arkadiusz Pawłowski](@/w/pan-pawlowski.md)'
  - Karolina (Pawłowski's real-life partner)
  - '[Wiktor Longman](@/w/wiktor-longman.md)'
  - '[Bad Bones](@/w/bad-bones.md), Marcin "Rzeźnik" Rzeźniczek'
  - g: true
    s: "Pawłowski's in-ring proposal"
    **x: [2] # Exclude Karolina from talent list**

Tymczasem jednak:

![image](https://github.com/user-attachments/assets/35a5ebe6-5a66-4870-a685-36ba2c3776bb)

**Comment by iwulOG** [comment]
kurde ja bym ją jednak zostawił bo była jakimś ubocznym elementem story, potem miała nawet drugi występ (UG21) jako follow up

**Comment by M3n747** [comment]
Brzmi sensownie - ale tak czy siak wygląda na to, że x: chyba nie działa.
