### ISSUE TITLE
Feedback: Kapitan Bazooka

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#395]
**Which page:** `w/kapitan-bazooka.md`
**Your feedback:** 
<on September 8th, 2024, Bazooka announced putting his career on hols indefinitely, due to an undisclosed condition of his joints.

https://www.instagram.com/p/C_qnN8Ii6hn/?igsh=MWNwd2JsM2hndDhsOQ%3D%3D >

**Comment by M3n747** [comment]
Poprawione parę drobiazgów przecinkowo-literkowych.
