### ISSUE TITLE
Feedback: KPW Championship

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#401]
**Which page:** `c/kpw-championship.md`
**Your feedback:** 
<Belt design:
Championship belt is rather modest in size and design. Main plate is a faded gold coloured vertical elipse with silver circle overlapped by bigger blue KPW logo in the middle. Main plate also contains the word "Champion" written on the bottom of main plate, and floristical engravings resembling a laurel wreath and a part of white eagle - polish coat of arms - at top of main plate. Full silouhettes of eagle are also adapted as sideplates. Plates are based on sturdy black leather strap.>

**Comment by k3rni** [comment]
Added in 50442c5

**Comment by SewiTheRef** [comment]
Merge has been się skopał

**Comment by k3rni** [comment]
Re-added in  90adba7
