### ISSUE TITLE
Feedback: DDW International Championship

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#408]
**Which page:** `c/ddw-international-championship.md`
**Your feedback:** 
<
Stats:
Shortest Reign: Kamil Aleksander 341 days
Oldest Champion: Joe E. Legend (41 years, 33 days)
Youngest Champion: Kamil Aleksander (24 years, 118 days)
Heaviest Champion: Joe E. Legend (121kg)
Lightest Champion: Kamil Aleksander (87kg)

Belt design:
In his design DDW International Championship pays homage to old-school championships from 80s era of US promotions. Most notably NWA World Heavyweight Championship. Main plate is round with horisontal rectangural protrusions in the middle. Main plate is golden-brass coloured with the blue globe symbol centralised on Europe and small DDW logo on top of the plate. Besides that main plate also contains some simple black ornaments and three red banners: top with flags (USA, Italy, UK, Germany, Japan, Mexico, Canada & France) displayed on it, middle with "international" and bottom with "champion" engraved. Both sides of Championship also featured two sideplates - one with big polish flag, and the second ones with DDW logo on it. Plates are based on standard black belt.

**Comment by M3n747** [comment]
#414
