### ISSUE TITLE
venue_page.html nie uwzględnia galerii

### ISSUE THREAD

**Issue by M3n747** [tpwres/teczki-polskiego-wrestlingu#426]
Dodałem grafiki do wpisu o [Nowym Haremie](https://tpwres.pl/v/atlantic-nh-gdynia/) - zbudowało się poprawnie, ale grafik nie wyświetla.

**Comment by k3rni** [comment]
Added in [d0fcb43](https://github.com/tpwres/teczki-polskiego-wrestlingu/commit/d0fcb43106d4af21116fe58e085c7348b0f50324)
