### ISSUE TITLE
Feedback: KPW OldTown Championship

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#430]
**Which page:** `c/kpw-old-town-championship.md`
**Your feedback:** 
<Belt design:
Original version of the belt was heavly influenced by the post-apocalyptic motive of OldTown Event. Its circural-shaped main plate was in fact part of rusty scrap metal without any visible logo, deliberate engravings or so. Instead of sideplates it only consisted of two smaller pieces of metal on both sides. All of the metal scrap plates were based on a red strap. Instead of regular snap fasteners used on normal belts, original OldTown Championship belt could be fastened by two slimmer leather belts, which were visibly longer than the red belt itself.
At KPW Arena 24 Rosetti introduced new variation of Championship. It diverged from the original concept of the belt to become more conservative in its design. Main plate become silver-coloured with black background and featured many engravings. Centre part of main plate is presenting a image of skull with post-apocaliptic mask inspired by famous "Mad Max" movie franchise, which is a homeage to OldTown event. Besides that the main plate also contains two banners with "KPW" written at top of the belt, and "Oldtown Champion" underneath. It is also decorated with many engravings resembling a barbed wire. Championship belt also contains two pairs of sideplates with a KPW logo on bigger pair of them, attached closer to the main plate. Plates are based on a regular black strap.

source: my eyes

**Comment by k3rni** [comment]
Added in #432
