### ISSUE TITLE
Feedback: PpW Piwo Przyjacielem Wrestlingu

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#431]
**Which page:** `e/ppw/2023-11-24-ppw-piwo-przyjacielem-wrestlingu.md`
**Your feedback:** 
<match 7 - missing Johnny Blade from Team Biesiad side
https://www.instagram.com/p/CzwcCcEhYfy/>

**Comment by M3n747** [comment]
#434

**Comment by k3rni** [comment]
Added in #434
