### ISSUE TITLE
Feedback: PpW Hardcore Friday 2

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#461]
**Which page:** `e/ppw/2024-09-20-ppw-hardcore-friday-2.md`
**Your feedback:** 
<Card, recap, personnel

Recap:
Hardcore Friday 2

20.09
no official transmission, but [fancam](https://www.youtube.com/watch?v=RtpLDFR-3v0&ab_channel=IstotaWrestlingu) from Istota Wrestlingu available 

PpW's host makes his entrance to "Koty z Mokotowa" (not recorded in the stream, but confirmed). He runs through the card of today's show and hypes up the crowd. Gustav Gryffin's music interrupts him.

Gustav, Olgierd & Isnorr make their entrance, Gustav wearing a suit cuts a promo about PpW's growth being due to Zmowa's actions. He lists the members:
Olgierd, prospective member Isnorr, Jakub Linde, Marco Hammers, Mister Z (named a "true messiah of polish wrestling" - shot at Pawlowski). Crowd boos and chants "Mister Zjeb". He lists previous champions, until he says the belt is a relic of the past, stomps on it and kicks it out of the ring. Olgierd unzips his sweatshirt to present Gustav with a new, personalised, white PpW Championship. He gets "fuck you" and "respect the belt" chants. He dares anyone who has a problem with this to get better and do something about it… but nobody can.

Michael HT makes his entrance to announce next match.
Referee Seweryn slides into the ring. Crowd chants for "violence".

Out next is Axel Fox.
He makes his entrance and calls out Mister Z or anybody else. Making his entrance, Adept Oskar, wearing all black, Young Lion style gear. Crowd makes fun of it with "show your ass", "wear some pants" and "show your dick" chants.
Fox offers a handshake, but Oskar refuses, establishing himself as a heel in this match. Crowd clearly on Fox's side. Oskar establishes early dominance with power moves and berating his smaller oponent. Fox makes a comeback, "this is awesome" chants erupt. Fox wins with a top rope elbow drop to a huge pop. He offers a handshake to the rookie, which he now accepts.
While Fox celebrates, some female fans want him to show his dick at backstage.

Referee Karol Górski makes his entrance, HT is back in the ring. He plugs the new offer, tickets for next show, Co za noc at discount.

Next match is "ustawka bez sprzętu" (hooligan street fight - no weapons) as per agreement between the two

Gabriel Queen v Olgierd
Gabriel Queen is out first, with crowd having fun to his Hannah Montana theme. Huge pop.

Out next is Olgierd to mostly boos. They start feeling out the crowd and there are now dueling chants for Olgierd and Gabriel. The match starts as a back and forth striking contest. Olgierd thwarts Queen's momentum with a slam, attempts a pinfall but only 1-count there. He continues working on Queen while the crowd chants for blood. After a missed headbutt, Queen gets a Chance for his comeback and he's on fire. The actions spills outside the ring, baseball bat is introduced. Referee hides the baseball bat under the ring, Queen uses this opportunity to make a Poetry-in-motion style jump back into the ring, off the referee's back, dropkicking Olgierd. Olgierd snaps, introduces the kendo stick into a match, pushes away the referee and pummels Queen.
As per match rules it's a DQ, Queen wins.

HT is back in the ring talking to the crowd.
Dostawczak match. Feager is out first with a sledgehammer to indifferent reaction and some boos. Biesiad is next, with crowd chanting along to his song. He immediately charges at Feager, throws a chair in his face and is on fire. Feager tossed out of the ring, Biesiad dives and they brawl to outside. Action is back to the ring with Feager now dominant. He beats Biesiad down with frying sheets and some of his trademark offense. Feager introduces a table into the ring, sets it up on the corner. Biesiad tries to suplex the table on to Feager, but he catches it and sets up in the opposite corner, thros Biesiad into it, breaking the table. Another table suplex spot, now Biesiad succeeds. Biesiad attempts a pinfall but is reminded - match can only be won by putting oponent into a van. After more action in the ring, they brawl towards the outside and the van. They brawl using the van and some railings set up due to area's reconstruction. Biesiad is thrown into the van and Feager closes one side of the door, then next… but Biesiad blocked the door with a board. He dives out of the van and makes his comeback on Feager. Now Feager is put in the van, Biesiad joins him and locks both of tchem inside. Referee starts the count and the van drives away to everyone's confusion. Referee confirms the match is not over. However HT confirms that Biesiad won. 

Winner: No-contest/Biesiad - wait for confirmation from PpW
The show comes to a break.

Back from the break
Referee of the match - Seweryn

Marcelito v Jacob Crane
Jacob Crane is out first, making a babyface entrance. Marcelito is next. They start trading technical offense.
It's now 21:37 and crowd starts to sing "Barka". Marcelito releases himself from Crane and starts his sequence of striking moves. Satellite DDT on Crane but only 2-count. Crane back with his offense, Emerald Flowsion for a 3-count.

Winner: Jacob Crane
Crane grabs a mic for a promo, he appreciates the crowd liking his ass and poses for the fans. He announces leaving for Japan for next 6 months, thanks the fans and wishes them to have fun for the rest of the show.

Anarchy Cyclone Tag Team Match
Isnorr & Gustav Gryffin v Johnny Blade & Samson.

Heel team makes their entrances - Isnorr first to moderate heel reaction, Gustav Gryffin.
Samson makes his entrance with a trash can full of weapons to a huge pop. Johnny Blade joins him with a makeshift mallet (water bin on a kendo stick). Heels start to beat down Samson during Blade's entrance, as he enters the ring, he makes a save and the match is even. Action spills outside the ring, Gryffin and Samson brawl at the bar table. Crowd urges Samson to kill Gryffin. Now, Gryffin and Blade fight in the ring, while Samson and Isnorr fight on the outside. Gryffin tosses Blade outside onto the other two. Samson and Gryffin in the ring, Gryffin lays Samson out with a chairshot. He continues to pummel Samson, while crowd urges Samson to fight back. He makes a comeback but it's shortly lived and Gryffin continues to punish him. Samson and Blade fight Isnorr for some nearfalls, eventually Gryffin makes his return to the ring. Gryffin is laid on the table, Samson with a frog splash for a near fall - Isnorr broke a pin from the outside. Low blow from Isnorr and heels get the upperhand. Gryffin straps Samson to the corner. They slam Blade through the board put on the chairs, while Samson is only able to watch helplessly.
Isnorr pins Blade for a 3 count

Winners
Isnorr and Gustav Gryffin.

Heels continue to pummel Blade with helpless Samson still in the corner. Olgierd joins other heels in a beatdown now and hits Braindead on Blade. Axel Fox enters for a save to monster pop. Masked figure lays him out with a kendo stick… it's Mister Z. They all beat Fox down and Biesiad is in, throwing some scaffolding into the ring. Heels back away and it looks like "Zmowa przeciwko zmowie" is finally formed. Babyfaces free Samson and they all celebrate together. Biesiad challenges Zet to "ustawka match" where each of them teams up with his respective crew. Some taunting between 2 teams and babyfaces celebrate once again to loud cheers and "PpW" chants.

Michael HT confirms for Co za noc:
Zmowa przeciwko zmowie vs Zmowa. HT plugs the next shows and announces start of ticket sale for the next day. Afterparty starts now.

Personnel: 
Host: "OG" Michael HT
Referees: Seweryn, Karol Górski/Gurski

Card, results:
Segment: Gustav Gryffin, Olgierd & Isnorr - Gustav reveals a new PpW Championship belt
Axel Fox vs Adept Oskar {include "adept" in Oskar's name as it's part of his "Young Lion" presentation)
Winner: Axel Fox
Gabriel Queen vs Olgierd  - Weapons not allowed ("ustawka bez sprzętu")
Winner:
Gabriel Queen via DQ - Olgierd used the kendo stick

Biesiad Strong vs Feager - Delivery van match (Dostawczak match)
Winner:
Apparently Biesiad as per HT's announcement over the show, but referee decision was unclear (he declared match continued after both got locked in the van which drove off)

Marcelito vs Jacob Crane
Winner: Jacob Crane

Isnorr & Gustav Gryffin v Johnny Blade & Samson - Anarchy Cyclone Tag Team Match
Winners: Isnorr & Gustav Gryffin

Closing segment - Zmowa vs Zmowa przeciwko zmowie face off
Axel Fox, Biesiad Strong, Gustav Gryffin, Johnny Blade, Mister Z, Olgierd, Samson
>

**Comment by M3n747** [comment]
#463
