### ISSUE TITLE
Feedback: PpW Championship

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#465]
**Which page:** `c/ppw-championship.md`
**Your feedback:** 
<Statistics & Belt Design:
Stats:
shortest reign: Biesiad Strong (<1 day)
Heaviest Champion: Steve Kuningas (120kg)
Lightest Champion: Osamu / Mister Z (85kg)

Belt design:
Original PpW Championship design which was used in early backyard days of PpW was rather simple and cheaply made. Main plate was in fact made of synthetic material instead of metal. It resembled a original WWE Tag Team Championship from Ruthless Agression Era in shape. Golden-coloured plate was decorated with black outlinings and details. In the centre of main plate there was orginal "PpW" logo in colour based on "eagle wings" ornamentation. Under that there was banner with word "MISTRZ" (eng. "CHAMPION") written on it. Over "PpW" logo it was also a ornament with Cross of Saint James on it. Lower part of main plate also contained a spot to put custom-made plate with name of a champion on it; however it was apparently never used. On both sides of main plate there was to sideplates visible, one with luchador mask, and the second one with "hardcore wrestling" written on it - a representation of both early-PpW brands "Hardcore Friday" and "Super Lucha". All of the plates were based on material mint-blue belt without any snap fasteners. Instead it could be fastened by velcro strap on the inner side of belt.

In february 2021 Mister Z introduced new version of Championship. This time it was much more representative and neatly done. Main plate was round and made of golden-coloured metal. In the centre of main plate there was large, updated "PpW" in silver colour. Under the logo there was a smaller banner with "Champion" written on it. Main plate was also lightly decorated with engravings and laurel wrath with some coloured gems on the sides. Sideplates were rather simple and circural with "PpW" logo on it. Plates were based on standard black leather belt.

At Hardcore Friday 2 Gustav Gryffin introduced new, personalized variation of PpW Championship. It was rather similar in design to the previous championship, with the main differences being the added colourful details (such as blue and red "PpW" logo), white belt instead of a black one, and golden tips with "PpW" logo at the ends of belt itself.

Source: my eyes
zalecam przejrzenie gramatyki i ortografii oraz inne poprawki stylistyczne bo mam usmażony mózg troszkę
>

**Comment by M3n747** [comment]
#459

**Comment by k3rni** [comment]
Added in #459
