### ISSUE TITLE
Feedback: PTW - Walczymy dla Fundacji

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#473]
**Which page:** `e/ptw/2024-09-29-ptw-walczymy-dla-fundacji.md`
**Your feedback:** 
<add stakes to Lopez v Puncher: PTW Championship match
Ref: https://www.facebook.com/PrimeTimeWrestlingPL/posts/pfbid0wNSGXfxshCdN5rSsBR7y7GYmkznqYNQkrTAFu4jJbR8EWqyzt8Hk9bZqLxqy7xRVl?__cft__[0]=AZWnW0ogzREbeq4cYAls3ff9i37PCw2nSeQfPhimF5oKGC_Td5U6RafageWpn3TgMZpT_xVq4-pf4AA3CEo_le5rCvFfoTK8Pi7Jej4BLFJ0ItENpQAxACEudIilP9ukzfJmafLHBFK7SunUWGEVwGCNysIzwy8fYv-yWTb2hHU7t-AfN4-gfeVV_uPNdxBjr7baf2nlAgq16ApQ915roc9zPCfJiPQdDiZhUHakNIxmEw&__tn__=%2CO%2CP-R

Add new match:
Alex Brave vs LaVonce
Ref:
https://www.facebook.com/PrimeTimeWrestlingPL/posts/pfbid0LNSQxUx7ABD5MehHccXpbYPVpa1ApabffPHkmiN1EizbhtVtMZPsnwXRGJSboD1nl?__cft__[0]=AZXIJ4CPJCVQnwjFGB_chwcPBwEP7paoLEKB-f3lVGeCHr-rU4Z6vWa-oeXezSHKmI4dhfshTSBzL87DkMcrT1QJ9tdozwqCNf2N3idtEv6QGfbP3eDr0I6lKZCCF9qa5ujqlJmtAks7_-JVzC9gn7VPiIQxDGDZdVJQkfkZ1OxazA&__tn__=%2CO%2CP-R>

**Comment by iwulOG** [comment]
![image](https://github.com/user-attachments/assets/0443b155-a066-488d-95ed-aa5751597971)
![image](https://github.com/user-attachments/assets/43ca06a5-4649-492c-aa1b-008f64343ac7)
Dodaję grafiki meczy - trzeba zachować dla potomności jakie to było paskudne :D

**Comment by M3n747** [comment]
#474

**Comment by k3rni** [comment]
Added in #474
