### ISSUE TITLE
Feedback: Grand Timeline

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#607]
**Which page:** `a/grand-timeline.md`
**Your feedback:** 
<Legacy of Wrestling, supercard project started by disgruntled PTW personalities manages to shatter the Forbidden Door. First time ever, KPW lends their performer (Filip Fux) to other Polish promotion>

**Comment by M3n747** [comment]
Jak ustaliliśmy na czacie, zaczekajmy może aż pojawi się pełna karta, żeby nie musieć edytować po kilka razy.
