### ISSUE TITLE
Sędzia Krystian Czekaj

### ISSUE THREAD

**Issue by k3rni** [tpwres/teczki-polskiego-wrestlingu#647]
1. Link to the chants article instead of explaining the phrase in detail
2. No longer the only ref to sell his own merch, Kornel has them too now https://www.facebook.com/photo?fbid=4041459702744483&set=a.2722224191334714. Update Kornel while we're at it.

**Comment by M3n747** [comment]
ad 1 - #652
ad 2 - 404

**Comment by k3rni** [comment]
Fixed both in #652
