### ISSUE TITLE
Feedback: Legacy of Wrestling

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#697]
**Which page:** `o/low.md`
**Your feedback:** 
<On November 11th, fans spotted a subsite dedicated to LoW at a website of Extreme Sports Channel - long-term home to wrestling in Poland, which recently entered a partnership to air Prime Time Wrestling shows. Though no word from promotion has been made yet, it led to assumptions that Legacy of Wrestling debut show is going to be aired on said channel.

https://www.extreme.com/pl/program/legacy-of-wrestling/>

**Comment by M3n747** [comment]
#698
