### ISSUE TITLE
Feedback: PTW#6: Total Blast From The Past

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#70]
**Which page:** `e/ptw/2024-05-11-ptw-6.md`
**Your feedback:** 
<Aigle Blanc vs Matt Sydal vs Jonny Storm was 3rd match in a card (after Nano Kaiden vs Starbuck Erik)
Intergender Tag Team Match was a CO-ME instead
>

**Comment by k3rni** [comment]
Updated in 93a097c
