### ISSUE TITLE
Feedback: KPW Arena 24: Zagrożenie Lawinowe

### ISSUE THREAD

**Issue by M3n747** [tpwres/teczki-polskiego-wrestlingu#73]
**Which page:** `e/kpw/2024-02-16-kpw-arena-24-zagrozenie-lawinowe.md`
**Your feedback:** 
Parę rzeczy hurtem, żeby się nie rozdrabniać.

* Ten trzeci przy graffiti WHITE BOYS to był Greg:
   https://i.imgur.com/lbdpiHW.jpeg
* Bracia Fux częściowo ogolili Chemika, ale właściwy wąsik namalowali markerem:
   https://i.imgur.com/dA9IGsN.jpeg
   https://i.imgur.com/uxCeNOD.jpeg (swoją drogą, zaskakujące podobieństwo na tym zdjęciu ;D)
* "Lesak bleed visibly" -> "Lesak bled visibly" (w końcu czas przeszły)
* "literally: Referee Penis" - dosłownie to "Referee Dick" przeca ;)

**Comment by k3rni** [comment]
Added in 8301bb4, but without the photos yet.

**Comment by M3n747** [comment]
> Added in [8301bb4](https://github.com/k3rni/teczki-polskiego-wrestlingu/commit/8301bb476c2966e0c2e34896d6d931aff1d5dc84), but without the photos yet.

W sumie zdjęcia dałem tylko na dowód, że nie wymyślam. :)
