### ISSUE TITLE
Feedback: PpW Piwo Przyjacielem Wrestlingu 2

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#739]
**Which page:** `e/ppw/2024-11-15-ppw-piwo-przyjacielem-wrestlingu-2.md`
**Your feedback:** 
_The only exception was Isnorr's title defense against Prince Striker._

Change to:

With exceptions of Isnorr's title defense against Prince Striker and Aron Wake vs Sambor

Source:
Interview from Co za noc where Sambor blames Wake for Fatal 4 way loss

**Comment by M3n747** [comment]
#741
