### ISSUE TITLE
Feedback: Prime Time Wrestling

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#76]
**Which page:** `o/ptw.md`
**Your feedback:** 
< 2024:
PTW 5: Gold Rush was held in Hotel Scout, Częstochowa, PL, not in Legionowo.

more high profile exits:
it is also worth noting, that both Olgierd & Marco Hammers kept the narrative that the are in PTW on social media even on the day of their ppw debut. Marco still feuded with Vincent Caravaggio on instagram & facebook (source), and both him and Olgierd posted a prepared instagram story with Prime Time Wrestling Neon from PTW PC on their story, keeping the narrative that they are on training in PTW.>

Also, if you are planning on adding "Foregin relations" and "polish wrestling scene" parts just like at MZW page:

Foregin Relations:
One of the main PTW selling points was a budget & ability to bring in a lot of pro wrestlers from abroad. At PTW 3: Legends it was announced that Santino Marella will become one of the co-owners of federation. This, however, was only a short-lived storyline angle lacking of any real payoff, leaving fans confused, when Santino made his return at PTW 5: Gold Rush only as an english-commentator and suprise entrant in Gold Rush Rumble.
Besides that PTW made an agreement with Krampus, who started his own federation in Austria called World Wrestling Austria. Federation was quickly renamed PTW: WWA, and it was de facto a "sister federation" runned by Krampus with assistance from Pawłowski. The cooperation allowed PTW talents to be booked at PTW: WWA show at 2024-01-05. 
PTW also made a cooperation with British Revolution Wrestling (BWR) which allowed BWR Champion Scotty Rawk to defend his championship in PTW. Agreement also allowed Diana Strong and Puncher to be booked at one of BWR shows in UK. 
One remarkable deal between PTW and bigger promotion was agreement with Impact Wrestling, when Joe Hendry was allowed to defend his Digital Media Championship against Trent Seven at PTW 3: Legends.

Polish wrestling scene:
Huge part of PTW roster in early days was combined of wrestlers from MZW, KPW or MCW, however PTW is known for its lack of interaction with other federations in Poland. Pro wrestlers in PTW were strictly prohibited from appearing in other polish federations, and any form of cooperation both as an performer or in a backstage role resulted in "firing" from PTW. This fact was one of the key factors leading to most of the PTW Exits, where the talents wanted to have a freedom of choice, and to take bookings from other polish federations. Same like in KPW: despise of other federations is inherited from Don Roid's running of DDW and Pawłowski attitude towards the "backyard" such as ppw.

source: I was there

![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/173069994/8b94ce7c-bc95-49d6-92ff-584a4bdc68f4)

**Comment by k3rni** [comment]
Added scene relations sections in c3c1c2a

**Comment by k3rni** [comment]
Added the screenshot in e3b722a. Noted in text that it linked to Tomicki's dating coaching site (but didn't link).
