### ISSUE TITLE
Feedback: The Greens

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#80]
**Which page:** `a/the-greens.md`
**Your feedback:** 
<
Madman Charlie / Karol Gurski nigdy nie był w PTW
Sewi The Ref (ja) debiutowałem jeszcze w MZW na Project Basement, potem zrobiłem bodajże jedno show z publiką w MZW przed transferem do PTW, więc to można również poprawić. >

**Comment by k3rni** [comment]
c106ccb
