### ISSUE TITLE
Feedback: Olgierd

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#81]
**Which page:** `w/olgierd.md`
**Your feedback:** 
<Bio Olgierda:

AKA: Hades (ppw), Krueger (MZW)

cagematch: https://www.cagematch.net/?id=2&nr=24693
działająca strona Hadesa na ppw wiki: https://web.archive.org/web/20230821192019/https://ppwofficial.fandom.com/pl/wiki/Hades

aktywny: 2016-obecnie

BIO:
2016-2018: PpW 
Olgierd występujący pod pseudonimem Hades zadebiutował w ppw w roku 2016, w czasach gdy federacja była jedynie backyardowym projektem.  W czasie dwuletniego pobytu w ppw stoczył pojedynki między innymi z takimi zawodnikami jak Mister Z, Faeger czy Rob Scaffold. W trakcie swojego pobytu w ppw specjalizował się w walkach hardcore'owych, przynależąc do rosteru "hardcore friday".

2018-2021 MZW i okazjonalne występy w PpW
Olgierd rozpoczął treningi w MZW w trakcie kursu letniego odbywającego się we Wrocławiu. W tamtym momencie zawiesił swoją współpracę w PpW. Na przełomie 2018/2019 roku był jednym z członków-założycieli ugrupowania "zielonych". Jego oficjalny ringowy debiut pod pseudonimem Kreuger miał miejsce na gali MZW Project 6: Death & Glory w Battle Royalu adeptów, gdzie został wyeliminowany przez Ring Rata (obecnie: Sędzia Seweryn). Wystąpił również na gali MZW Project 7: Golden Road i galch z cyklu Project Basement. Jego ostatni występ w MZW przypada na galę MZW Project 8: Golden Road FINALS gdzie zmierzył się z Isnorrem oraz Detim Blackiem w Triple Threat Matchu.
Z wiązku z popandemicznym rozluźnieniem i nieregularnym harmonogramem MZW Olgierd dwukrotnie wystąpił w PpW. Podczas gali PpW Ledwo Legalne w hardcore matchu przeciwko Johnny'emu Blade, oraz w kilku matchach podczas PpW Poznań Supershow 2021.
Olgierd oficjalnie opuścił MZW 29 października 2021 roku w trakcie zielonej rewolucji (większość wrestlerów MZW opuściła federację jednocześnie, właśnie tego dnia. Wśród nich prócz Olgierda byli również Rafael Kid, Madman Charlie, Isnorr, Sędzia Sewi i Aron Wake - przyp. red.). 

2021-2024 PTW
Niedługo po opuszczeniu MZW Olgierd kontynuował treningi i rozwój w Prime Time Wrestling, gdzie zadebiutował w trakcie gali PTW Underground 13 mierząc się z Robertem Starem. Niedługo później sformował on tag team wraz z Marco Hammersem - i menadżerką/dziewczyną Karyną -, który nazwany został "Legią Łysych".
Do najważniejszych walk z jego pobytu w PTW wymienić można dwie walki w stypulacji Street Fight - jedna z Gabrielem Queenem, oraz druga w świątecznym street fighcie z Axelem Foxem. Prócz tego Olgierd zawalczył również w Gold Rush Rumble Matchu o pas mistrzowski PTW, oraz Intergender Tag Team Matchu przeciwko Heidi Katrinie oraz Dianie Strong.

2024- Niespodziewany powrót do PpW Ewenement
Olgierd wraz z Marco Hammersem jako Legia Łysych dołączyli do PpW w trakcie gali PpW Ledwo Legalne IV niespodziewanie odpowiadając na open challenge wystosowany przez Pure Gold, którzy prowokowali oponentów w social mediach. Mimo to Legia Łysych praktycznie do momentu debiutu utrzymywała iluzję, jakoby wciąż pozostawali lojalni PTW. Niespodziewany debiut zakończył się zwycięstwem Legii Łysych i oficjalnym potwierdzeniem transferu do PpW.

Trivia:
Olgierd przez całą swą karierę za swój theme song obiera utwory polskiego rapera - wykonawcy muzyki horrorcore - Słonia. Były to kolejnio:
- PpW & MZW (Jako Hades i Krueger) - Słoń/Mikser - Początek Końca
- PTW (Solo) - Słoń - Sicario
- PTW & PpW (Jako legia łysych) - Słoń/Mikser/WSRH - Fopa i Nietakt

**Comment by k3rni** [comment]
Added in f6911c8
