### ISSUE TITLE
Feedback: Adam Bravo

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#82]
**Which page:** `w/adam-bravo.md`
**Your feedback:** 
<maybe reflect somewhat his non-run in PTW?
Even with "Post his KPW run, Bravo became affiliated with PTW and focused his social media on promoting the project, but failed to make a single on-air appearance"
References: https://www.facebook.com/BravoAdamPL>

**Comment by k3rni** [comment]
Live now https://tpwres.pl/w/adam-bravo/
