### ISSUE TITLE
Feedback: PTW#5: Gold Rush

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#84]
**Which page:** `e/ptw/2024-02-03-ptw-5-gold-rush.md`
**Your feedback:** 
<card,
Add 8:
Closing segment.
Pawłowski's in ring proposal
Members: Karolina (Pawłowski's real life partner), Arkadiusz Pawłowski, Wiktor Longman + on recording: Bad Bones, Marcin "Rzeźnik" Rzeźniczek
brief overview: Pawłowski proposes to his girlfriend but Longman interrupts. He shows the recording about PTW 4 Mystery kidnapping of Rzeźniczek being an elaborate ruse, hits Pawłowski with _At your service_ and closes the show with lottery plug.

**Comment by k3rni** [comment]
Added the segment in e3191c6, but that now causes Karolina to be listed among PTW's performers. I'm okay with that, she can have her one appearance (so does Najman). The text about what happened is already present in the recap, but without the link to Mystery.

**Comment by k3rni** [comment]
Added link in 4c75f8e
