### ISSUE TITLE
Feedback: MZW Project 6: Death & Glory

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#86]
**Which page:** `e/mzw/2019-08-24-mzw-project-6-death-and-glory.md`
**Your feedback:** 
<Battle royal squad:
- Aron Wake
- Nathan Cross (Gabriel Queen) (Runner-up!)
- Stanisław Van Dobroniak
- Anatolii
- Ring Rat (Referee Seweryn)
- Isnorr 
- Krueger (Olgierd)
probably someone else too, but I'm like 75% positive that the rest didn't get more matches at PSV.

source: I was there >

**Comment by k3rni** [comment]
cd3d5fe
