### ISSUE TITLE
Feedback: Gabriel Queen

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#87]
**Which page:** `w/gabriel-queen.md`
**Your feedback:** 
<Gabriel Queen bio:

active: 2019-current
ref: Gabriel Queen cagematch - https://www.cagematch.net/?id=2&nr=24919&name=Gabriel+Queen

2018-2021 MZW
Gabriel Queen started his pro wrestling career at MZW academy, being trained by Justin Joy, Asmund and Shadow. He made his debut in adept battle royal at MZW Project 6: Death & Glory being a runner-up and eventually losing to Aron Wake. He made his singles match debut at MZW Project 7: Golden Road, where he was defeated by Axel Fox. During that time he also became the one of founding members of "The Greens". He also made apperance at MZW taped shows during pandemic, called "MZW Project Basement", where he was managed by Isnorr. After making his final apperance during MZW Project Basement 4 he left the company

2021-2023 PTW
Shortly after leaving MZW Gabriel Queen joined PTW, making his debut as a joker in a battle royal during PTW 1# REVOLUCJA, where he was eliminated first. He then continued his career in PTW becoming one of the workhorses in a federeation, with a long-lasting streak of apperances on every PTW show. 
After Vic Golden debut in PTW they quickly formed a tag team called Pure Gold. Being the main and most popular heel faction during that time they feuded with PAKA (Disco Pablo, Boro & Taras) from June 2022 until June 2023 and PTW 4: The Mystery show, when they lost a tables match for PTW Tag Team Championship.
Shortly after that loss Vic Golden suffered a injury, and was sidelined for couple of months never making his PTW return. During that time Gabriel Queen shortly alligned with Legia Łysych (Marco Hammers, Olgierd and Karyna), but the alliance was quickly turned into a feud, which resulted in a loss against Olgierd in street fight match, and a victory against Marco Hammers at PTW Underground 18. That show makes his last apperance in PTW ring.
During that time he also started taking booking from abroad, making his apperances in Austria, Germany and Denmark.

2024 PpW
Gabriel Queen made his debiut at PpW: Miasto Bezprawia, where he faced Jacob Crane. After securing a victory he was attacked by defeated opponent, however his tag team partner - Vic Golden - made an PpW debut by saving him from a beatdown. Reunited tag team issued a open challange at PpW: Ledwo Legalne IV, which was suprisingly accepted by Legia Łysych. That reignited their feud back from PTW days.

**Comment by k3rni** [comment]
Added in a4b5dde
