### ISSUE TITLE
Feedback: PTW Exits

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#88]
**Which page:** `a/ptw-exits.md`
**Your feedback:** 
<Axel Fox status up in the air - Puncher declared he's out
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/ef8169c2-6cbf-4264-ba22-917214a71e85)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/b07c8fa4-a08d-4637-86bf-d8fa400a2f45)

Alex Brave (S.Rafał) forgotten, but still on the roster
>

**Comment by k3rni** [comment]
Added fox in ebaac3b, and a screenshot of Puncher leaking the info in cde2f3e.
