### ISSUE TITLE
Feedback: Krystian Czekaj

### ISSUE THREAD

**Issue by krystianczekaj** [tpwres/teczki-polskiego-wrestlingu#887]
Cześć, z tej strony Krystian Czekaj.

Przypadkowo natknąłem się na tę stronę i ją po krótce przejrzałem. Jeśli chodzi o moją postać warto zaktualizować to, że od kiedy jestem w KPW każdą galę nie tylko sędziowałem, ale też komentowałem. Poza tym również pracowałem dla federacji Do or Die Wrestling od 2013 do 2015 roku jako announcer oraz sędzia.

Pozdrawiam

**Comment by M3n747** [comment]
O komentowaniu była już w artykule wzmianka. Natomiast co do DDW, to tak mi się coś wydawało, że sędzia na [All or Nothing II](@/w/2014-08-17-ddw-all-or-nothing-2.md) wygląda jakoś dziwnie znajomo. ;) Jeżeli pamiętasz które gale sędziowałeś/prowadziłeś, to od razu byśmy dopisali.
