### ISSUE TITLE
Feedback: PTW Exits

### ISSUE THREAD

**Issue by iwulOG** [tpwres/teczki-polskiego-wrestlingu#92]
**Which page:** `a/ptw-exits.md`
**Your feedback:** 
<add - Axel Fox, undisclosed date. Him being out of company confirmed directly by Pawłowski on his twitch stream 25.06
reference:
https://www.twitch.tv/videos/2180575222>

**Comment by k3rni** [comment]
Added Fox's exit to the listing in https://github.com/tpwres/teczki-polskiego-wrestlingu/commit/ebaac3baa3817115b9d9dc6f29ac710adaa69e2f, and a line to PTW article in https://github.com/tpwres/teczki-polskiego-wrestlingu/commit/1493c6cbc3fe6a198504162db7154b1a7fd39c3b
