### ISSUE TITLE
Zgłoszenie Taras - matchfinder źle wyświetla wynik waleczki dla jego

### ISSUE THREAD

**Issue by SewiTheRef** [tpwres/teczki-polskiego-wrestlingu#947]
![467468820_575999468625480_733165286836503034_n](https://github.com/user-attachments/assets/c66dad75-f53c-4f92-8abc-4fc26d933f77)

**Comment by k3rni** [comment]
https://github.com/tpwres/matchfinder/pull/1

**Comment by k3rni** [comment]
Fixed in the above. Note also that Taras' screenshot shows the match date obscured by org logo, which was also fixed in https://github.com/tpwres/matchfinder/pull/2.
