### ISSUE TITLE
Feedback: Dawid Oliwa

### ISSUE THREAD

**Issue by M3n747** [tpwres/teczki-polskiego-wrestlingu#95]
**Which page:** `w/dawid-oliwa.md`
**Your feedback:** 
Globalny błąd: wszędzie jest "Dawid Oliwa", zamiast "David Oliwa" (główny artykuł, wpisy o galach, pewnie coś jeszcze).

https://www.facebook.com/FFDavidOliwa/
https://www.instagram.com/david_oliwa_wrestler/

**Comment by k3rni** [comment]
Merged in #97, added social media links in 5d0ba8c
